# Sun Dec 20 12:19:38 2020 ------------------------------

default:
# database
    dbname:                 "fd_reports"
    username:               "fd_reports_user"
    password:               "6Pb27%n_jH6J^@r&gJR-KbSxp--+8TBK"
    host:                   "rdsamazon.cbief3wnjkp9.eu-west-1.rds.amazonaws.com"
    encoding:               "latin1"
    
    table_leads_raw:        "bs_leads"
    table_leads_clean:      "bs_leads_clean"
    table_leads_log:        "bs_leads_log"
    table_leads_agg:        "bs_leads_aggr"
    table_available_cash:   "bs_leads_available_cash"
    table_lead_status:      "bs_leads_status"
    table_website_geo:      "bs_leads_geo"
    
    table_profiles_raw:     "bs_profiles"
    table_profiles_clean:   "bs_profiles_clean_tmp"
    table_profiles_log:     "bs_profiles_log"
    table_profiles_status:  "bs_profiles_status_aggr"
    table_profiles_currencies: "bs_profiles_currencies_aggr"
    
    scripts_dir:            "00_scripts"
    data_dir:               "00_data"

# general charting
    plot_color:             "#CA0813"
    plot_light_color:       "#FC9272"
    line_thickness:         1

# report 9
    window_months:  3
    
development:
    data_dir:       "../00_data"
    scripts_dir:    "../00_scripts"
    data_file:      "bs_10_all.Rds"

# general charting
    plot_color:             "#CA0813"
    plot_light_color:       "#FC9272"
    line_thickness:         1
